### PR TITLE
added example for blocking subprocess

### PR DESCRIPTION
**Pull request by aranvir**
Follow-up on https://github.com/Flared/dramatiq-abort/issues/22

Brief example for how to deal with a subprocess or any similar blocking call.

### CODE REVIEW

**Comment by aranvir** [comment]
Not sure why 3.7 is not building.. Haven't worked with .rst before and my local make did not work, but since it's only docs I thought it would be fine.

Is there a new-line necessary between `..code-block::` and `@dramatiq.actor`?
```
.. code-block::
  @dramatiq.actor
  def my_subprocess():
```

**Comment by isra17** [comment]
Seems like 3.7 have been broken for a little while. Not sure why, but I can stil merge your work and fix the 3.7 anotehr time.

**Comment by aranvir** [comment]
Quick follow up: Could be that it's really the missing newline that messes with the rendering..
Sorry!

image

**Comment by isra17** [comment]
Fixed!

**Pull request merged**
